export const NAHMII_DEPOSIT = 'src/WalletHOC/NAHMII/NAHMII_DEPOSIT';
export const NAHMII_DEPOSIT_ETH = 'src/WalletHOC/NAHMII/NAHMII_DEPOSIT_ETH';
export const NAHMII_DEPOSIT_ETH_SUCCESS = 'src/WalletHOC/NAHMII/NAHMII_DEPOSIT_ETH_SUCCESS';
export const NAHMII_DEPOSIT_FAILED = 'src/WalletHOC/NAHMII/NAHMII_DEPOSIT_FAILED';
export const NAHMII_APPROVE_TOKEN_DEPOSIT = 'src/WalletHOC/NAHMII/NAHMII_APPROVE_TOKEN_DEPOSIT';
export const NAHMII_APPROVE_TOKEN_DEPOSIT_SUCCESS = 'src/WalletHOC/NAHMII/NAHMII_APPROVE_TOKEN_DEPOSIT_SUCCESS';
export const NAHMII_COMPLETE_TOKEN_DEPOSIT = 'src/WalletHOC/NAHMII/NAHMII_COMPLETE_TOKEN_DEPOSIT';
export const NAHMII_COMPLETE_TOKEN_DEPOSIT_SUCCESS = 'src/WalletHOC/NAHMII/NAHMII_COMPLETE_TOKEN_DEPOSIT_SUCCESS';

export const MAKE_NAHMII_PAYMENT = 'src/WalletHOC/NAHMII/MAKE_NAHMII_PAYMENT';
export const MAKE_NAHMII_PAYMENT_SUCCESS = 'src/WalletHOC/NAHMII/MAKE_NAHMII_PAYMENT_SUCCESS';
export const MAKE_NAHMII_PAYMENT_ERROR = 'src/WalletHOC/NAHMII/MAKE_NAHMII_PAYMENT_ERROR';

export const LOAD_NAHMII_BALANCES = 'src/WalletHOC/NAHMII/LOAD_NAHMII_BALANCES';
export const LOAD_NAHMII_BALANCES_SUCCESS = 'src/WalletHOC/NAHMII/LOAD_NAHMII_BALANCES_SUCCESS';
export const LOAD_NAHMII_BALANCES_ERROR = 'src/WalletHOC/NAHMII/LOAD_NAHMII_BALANCES_ERROR';
export const LOAD_NAHMII_STAGED_BALANCES = 'src/WalletHOC/NAHMII/LOAD_NAHMII_STAGED_BALANCES';
export const LOAD_NAHMII_STAGED_BALANCES_SUCCESS = 'src/WalletHOC/NAHMII/LOAD_NAHMII_STAGED_BALANCES_SUCCESS';
export const LOAD_NAHMII_STAGED_BALANCES_ERROR = 'src/WalletHOC/NAHMII/LOAD_NAHMII_STAGED_BALANCES_ERROR';
export const LOAD_NAHMII_STAGING_BALANCES = 'src/WalletHOC/NAHMII/LOAD_NAHMII_STAGING_BALANCES';
export const LOAD_NAHMII_STAGING_BALANCES_SUCCESS = 'src/WalletHOC/NAHMII/LOAD_NAHMII_STAGING_BALANCES_SUCCESS';
export const LOAD_NAHMII_STAGING_BALANCES_ERROR = 'src/WalletHOC/NAHMII/LOAD_NAHMII_STAGING_BALANCES_ERROR';

export const ENABLE_NAHMII_MAINNET = 'src/WalletHOC/NAHMII/ENABLE_NAHMII_MAINNET';
export const DISABLE_NAHMII_MAINNET = 'src/WalletHOC/NAHMII/DISABLE_NAHMII_MAINNET';

export const HIDE_DISCLAIMER_BTN = 'src/WalletHOC/NAHMII/HIDE_DISCLAIMER_BTN';
export const SHOW_DISCLAIMER_BTN = 'src/WalletHOC/NAHMII/SHOW_DISCLAIMER_BTN';
