export const MAKE_NAHMII_PAYMENT = 'src/WalletHOC/NAHMII/MAKE_NAHMII_PAYMENT';
export const MAKE_NAHMII_PAYMENT_SUCCESS = 'src/WalletHOC/NAHMII/MAKE_NAHMII_PAYMENT_SUCCESS';
export const MAKE_NAHMII_PAYMENT_ERROR = 'src/WalletHOC/NAHMII/MAKE_NAHMII_PAYMENT_ERROR';

export const LOAD_NAHMII_BALANCES = 'src/WalletHOC/NAHMII/LOAD_NAHMII_BALANCES';
export const LOAD_NAHMII_BALANCES_SUCCESS = 'src/WalletHOC/NAHMII/LOAD_NAHMII_BALANCES_SUCCESS';
export const LOAD_NAHMII_BALANCES_ERROR = 'src/WalletHOC/NAHMII/LOAD_NAHMII_BALANCES_ERROR';
export const LOAD_NAHMII_STAGED_BALANCES = 'src/WalletHOC/NAHMII/LOAD_NAHMII_STAGED_BALANCES';
export const LOAD_NAHMII_STAGED_BALANCES_SUCCESS = 'src/WalletHOC/NAHMII/LOAD_NAHMII_STAGED_BALANCES_SUCCESS';
export const LOAD_NAHMII_STAGED_BALANCES_ERROR = 'src/WalletHOC/NAHMII/LOAD_NAHMII_STAGED_BALANCES_ERROR';
export const LOAD_NAHMII_STAGING_BALANCES = 'src/WalletHOC/NAHMII/LOAD_NAHMII_STAGING_BALANCES';
export const LOAD_NAHMII_STAGING_BALANCES_SUCCESS = 'src/WalletHOC/NAHMII/LOAD_NAHMII_STAGING_BALANCES_SUCCESS';
export const LOAD_NAHMII_STAGING_BALANCES_ERROR = 'src/WalletHOC/NAHMII/LOAD_NAHMII_STAGING_BALANCES_ERROR';
