export const NAHMII_DEPOSIT = 'src/NahmiiHoc/NAHMII_DEPOSIT';
export const NAHMII_DEPOSIT_ETH = 'src/NahmiiHoc/NAHMII_DEPOSIT_ETH';
export const NAHMII_DEPOSIT_ETH_SUCCESS = 'src/NahmiiHoc/NAHMII_DEPOSIT_ETH_SUCCESS';
export const NAHMII_DEPOSIT_FAILED = 'src/NahmiiHoc/NAHMII_DEPOSIT_FAILED';
export const NAHMII_APPROVE_TOKEN_DEPOSIT = 'src/NahmiiHoc/NAHMII_APPROVE_TOKEN_DEPOSIT';
export const NAHMII_APPROVE_TOKEN_DEPOSIT_SUCCESS = 'src/NahmiiHoc/NAHMII_APPROVE_TOKEN_DEPOSIT_SUCCESS';
export const NAHMII_COMPLETE_TOKEN_DEPOSIT = 'src/NahmiiHoc/NAHMII_COMPLETE_TOKEN_DEPOSIT';
export const NAHMII_COMPLETE_TOKEN_DEPOSIT_SUCCESS = 'src/NahmiiHoc/NAHMII_COMPLETE_TOKEN_DEPOSIT_SUCCESS';

export const MAKE_NAHMII_PAYMENT = 'src/NahmiiHoc/MAKE_NAHMII_PAYMENT';
export const MAKE_NAHMII_PAYMENT_SUCCESS = 'src/NahmiiHoc/MAKE_NAHMII_PAYMENT_SUCCESS';
export const MAKE_NAHMII_PAYMENT_ERROR = 'src/NahmiiHoc/MAKE_NAHMII_PAYMENT_ERROR';

export const LOAD_NAHMII_BALANCES = 'src/NahmiiHoc/LOAD_NAHMII_BALANCES';
export const LOAD_NAHMII_BALANCES_SUCCESS = 'src/NahmiiHoc/LOAD_NAHMII_BALANCES_SUCCESS';
export const LOAD_NAHMII_BALANCES_ERROR = 'src/NahmiiHoc/LOAD_NAHMII_BALANCES_ERROR';
export const LOAD_NAHMII_STAGED_BALANCES = 'src/NahmiiHoc/LOAD_NAHMII_STAGED_BALANCES';
export const LOAD_NAHMII_STAGED_BALANCES_SUCCESS = 'src/NahmiiHoc/LOAD_NAHMII_STAGED_BALANCES_SUCCESS';
export const LOAD_NAHMII_STAGED_BALANCES_ERROR = 'src/NahmiiHoc/LOAD_NAHMII_STAGED_BALANCES_ERROR';
export const LOAD_NAHMII_STAGING_BALANCES = 'src/NahmiiHoc/LOAD_NAHMII_STAGING_BALANCES';
export const LOAD_NAHMII_STAGING_BALANCES_SUCCESS = 'src/NahmiiHoc/LOAD_NAHMII_STAGING_BALANCES_SUCCESS';
export const LOAD_NAHMII_STAGING_BALANCES_ERROR = 'src/NahmiiHoc/LOAD_NAHMII_STAGING_BALANCES_ERROR';

export const ENABLE_NAHMII_MAINNET = 'src/NahmiiHoc/ENABLE_NAHMII_MAINNET';
export const DISABLE_NAHMII_MAINNET = 'src/NahmiiHoc/DISABLE_NAHMII_MAINNET';

export const HIDE_DISCLAIMER_BTN = 'src/NahmiiHoc/HIDE_DISCLAIMER_BTN';
export const SHOW_DISCLAIMER_BTN = 'src/NahmiiHoc/SHOW_DISCLAIMER_BTN';

export const LOAD_NAHMII_RECEIPTS = 'src/WalletHOC/NAHMII/LOAD_NAHMII_RECEIPTS';
export const LOAD_NAHMII_RECEIPTS_SUCCESS = 'src/WalletHOC/NAHMII/LOAD_NAHMII_RECEIPTS_SUCCESS';
export const LOAD_NAHMII_RECEIPTS_ERROR = 'src/WalletHOC/NAHMII/LOAD_NAHMII_RECEIPTS_ERROR';
