/*
 *
 * WalletHoc constants
 *
 */

export const SET_CURRENT_WALLET = 'src/WalletHOC/SET_CURRENT_WALLET';

export const INIT_WALLETS_BALANCES = 'src/WalletHOC/INIT_WALLETS_BALANCES';

export const LOAD_WALLET_BALANCES = 'src/WalletHOC/LOAD_WALLET_BALANCES';
export const LOAD_WALLET_BALANCES_SUCCESS = 'src/WalletHOC/LOAD_WALLET_BALANCES_SUCCESS';
export const LOAD_WALLET_BALANCES_ERROR = 'src/WalletHOC/LOAD_WALLET_BALANCES_ERROR';

export const LOAD_SUPPORTED_TOKENS = 'src/WalletHOC/LOAD_SUPPORTED_TOKENS';
export const LOAD_SUPPORTED_TOKENS_SUCCESS = 'src/WalletHOC/LOAD_SUPPORTED_TOKENS_SUCCESS';
export const LOAD_SUPPORTED_TOKENS_ERROR = 'src/WalletHOC/LOAD_SUPPORTED_TOKENS_ERROR';

export const LOAD_PRICES = 'src/WalletHOC/LOAD_PRICES';
export const LOAD_PRICES_SUCCESS = 'src/WalletHOC/LOAD_PRICES_SUCCESS';
export const LOAD_PRICES_ERROR = 'src/WalletHOC/LOAD_PRICES_ERROR';

export const CREATE_WALLET_FROM_MNEMONIC = 'src/WalletHOC/CREATE_WALLET_FROM_MNEMONIC';
export const CREATE_WALLET_FROM_PRIVATE_KEY = 'src/WalletHOC/CREATE_WALLET_FROM_PRIVATE_KEY';
export const CREATE_WALLET_SUCCESS = 'src/WalletHOC/CREATE_WALLET_SUCCESS';
export const CREATE_WALLET_FAILURE = 'src/WalletHOC/CREATE_WALLET_FAILURE';

export const ADD_NEW_WALLET = 'src/WalletHOC/ADD_NEW_WALLET';

export const DELETE_WALLET = 'src/WalletHOC/DELETE_WALLET';

export const DECRYPT_WALLET = 'src/WalletHOC/DECRYPT_WALLET';
export const DECRYPT_WALLET_SUCCESS = 'src/WalletHOC/DECRYPT_WALLET_SUCCESS';
export const DECRYPT_WALLET_FAILURE = 'src/WalletHOC/DECRYPT_WALLET_FAILURE';

export const SHOW_DECRYPT_WALLET_MODAL = 'src/WalletHOC/SHOW_DECRYPT_WALLET_MODAL';
export const HIDE_DECRYPT_WALLET_MODAL = 'src/WalletHOC/HIDE_DECRYPT_WALLET_MODAL';

export const TRANSACTION_CONFIRMED = 'src/WalletHOC/TRANSACTION_CONFIRMED';

export const TRANSFER = 'src/WalletHOC/TRANSFER';
export const TRANSFER_ETHER = 'src/WalletHOC/TRANSFER_ETHER';
export const TRANSFER_ERC20 = 'src/WalletHOC/TRANSFER_ERC20';
export const TRANSFER_SUCCESS = 'src/WalletHOC/TRANSFER_SUCCESS';
export const TRANSFER_ERROR = 'src/WalletHOC/TRANSFER_ERROR';

// Ledger Nano S constants
export const LEDGER_CONNECTED = 'src/WalletHOC/LEDGER_CONNECTED';
export const LEDGER_DISCONNECTED = 'src/WalletHOC/LEDGER_DISCONNECTED';
export const LEDGER_ETH_CONNECTED = 'src/WalletHOC/LEDGER_ETH_CONNECTED';
export const LEDGER_ETH_DISCONNECTED = 'src/WalletHOC/LEDGER_ETH_DISCONNECTED';
export const FETCH_LEDGER_ADDRESSES = 'src/WalletHOC/FETCH_LEDGER_ADDRESSES';
export const FETCHED_LEDGER_ADDRESS = 'src/WalletHOC/FETCHED_LEDGER_ADDRESS';
export const SAVE_LEDGER_ADDRESS = 'src/WalletHOC/SAVE_LEDGER_ADDRESS';
export const INIT_LEDGER = 'src/WalletHOC/INIT_LEDGER';
export const LEDGER_ERROR = 'src/WalletHOC/LEDGER_ERROR';
