/*
 *
 * WalletHoc constants
 *
 */

export const SET_CURRENT_WALLET = 'src/WalletHOC/SET_CURRENT_WALLET';


export const CREATE_WALLET_FROM_MNEMONIC = 'src/WalletHOC/CREATE_WALLET_FROM_MNEMONIC';
export const CREATE_WALLET_FROM_PRIVATE_KEY = 'src/WalletHOC/CREATE_WALLET_FROM_PRIVATE_KEY';
export const CREATE_WALLET_SUCCESS = 'src/WalletHOC/CREATE_WALLET_SUCCESS';
export const CREATE_WALLET_FAILURE = 'src/WalletHOC/CREATE_WALLET_FAILURE';

export const ADD_NEW_WALLET = 'src/WalletHOC/ADD_NEW_WALLET';

export const DELETE_WALLET = 'src/WalletHOC/DELETE_WALLET';

export const DECRYPT_WALLET = 'src/WalletHOC/DECRYPT_WALLET';
export const DECRYPT_WALLET_SUCCESS = 'src/WalletHOC/DECRYPT_WALLET_SUCCESS';
export const DECRYPT_WALLET_FAILURE = 'src/WalletHOC/DECRYPT_WALLET_FAILURE';

export const SHOW_DECRYPT_WALLET_MODAL = 'src/WalletHOC/SHOW_DECRYPT_WALLET_MODAL';
export const HIDE_DECRYPT_WALLET_MODAL = 'src/WalletHOC/HIDE_DECRYPT_WALLET_MODAL';

export const TRANSACTION_CONFIRMED = 'src/WalletHOC/TRANSACTION_CONFIRMED';

export const TRANSFER = 'src/WalletHOC/TRANSFER';
export const TRANSFER_ETHER = 'src/WalletHOC/TRANSFER_ETHER';
export const TRANSFER_ERC20 = 'src/WalletHOC/TRANSFER_ERC20';
export const TRANSFER_SUCCESS = 'src/WalletHOC/TRANSFER_SUCCESS';
export const TRANSFER_ERROR = 'src/WalletHOC/TRANSFER_ERROR';

export const LOAD_BLOCK_HEIGHT = 'src/WalletHOC/LOAD_BLOCK_HEIGHT';
export const LOAD_BLOCK_HEIGHT_SUCCESS = 'src/WalletHOC/LOAD_BLOCK_HEIGHT_SUCCESS';
export const LOAD_BLOCK_HEIGHT_ERROR = 'src/WalletHOC/LOAD_BLOCK_HEIGHT_ERROR';
