/*
 *
 * WalletHoc constants
 *
 */

export const SET_CURRENT_WALLET = 'src/WalletHOC/SET_CURRENT_WALLET';
export const LOAD_WALLETS = 'src/WalletHOC/LOAD_WALLETS';
export const LOAD_WALLETS_SUCCESS = 'src/WalletHOC/LOAD_WALLETS_SUCCESS';

export const LOAD_WALLET_BALANCES = 'src/WalletHOC/LOAD_WALLET_BALANCES';
export const LOAD_WALLET_BALANCES_SUCCESS = 'src/WalletHOC/LOAD_WALLET_BALANCES_SUCCESS';
export const LOAD_WALLET_BALANCES_ERROR = 'src/WalletHOC/LOAD_WALLET_BALANCES_ERROR';
export const LISTEN_TOKEN_BALANCES = 'src/WalletHOC/LISTEN_TOKEN_BALANCES';
export const UPDATE_TOKEN_BALANCES = 'src/WalletHOC/UPDATE_TOKEN_BALANCES';

export const CREATE_WALLET_FROM_MNEMONIC = 'src/WalletHOC/CREATE_WALLET_FROM_MNEMONIC';
export const CREATE_WALLET_FROM_PRIVATE_KEY = 'src/WalletHOC/CREATE_WALLET_FROM_PRIVATE_KEY';
export const CREATE_WALLET_SUCCESS = 'src/WalletHOC/CREATE_WALLET_SUCCESS';
export const CREATE_WALLET_FAILURE = 'src/WalletHOC/CREATE_WALLET_FAILURE';

export const ADD_NEW_WALLET = 'src/WalletHOC/ADD_NEW_WALLET';

export const DECRYPT_WALLET = 'src/WalletHOC/DECRYPT_WALLET';
export const DECRYPT_WALLET_SUCCESS = 'src/WalletHOC/DECRYPT_WALLET_SUCCESS';
export const DECRYPT_WALLET_FAILURE = 'src/WalletHOC/DECRYPT_WALLET_FAILURE';

export const SHOW_DECRYPT_WALLET_MODAL = 'src/WalletHOC/SHOW_DECRYPT_WALLET_MODAL';
export const HIDE_DECRYPT_WALLET_MODAL = 'src/WalletHOC/HIDE_DECRYPT_WALLET_MODAL';

export const TRANSFER = 'src/WalletHOC/TRANSFER';
export const TRANSFER_ETHER = 'src/WalletHOC/TRANSFER_ETHER';
export const TRANSFER_ERC20 = 'src/WalletHOC/TRANSFER_ERC20';
export const TRANSFER_SUCCESS = 'src/WalletHOC/TRANSFER_SUCCESS';
export const TRANSFER_ERROR = 'src/WalletHOC/TRANSFER_ERROR';

// Ledger Nano S constants
export const POLL_LEDGER = 'src/WalletHOC/POLL_LEDGER';
export const START_LEDGER_SYNC = 'src/WalletHOC/START_LEDGER_SYNC';
export const STOP_LEDGER_SYNC = 'src/WalletHOC/STOP_LEDGER_SYNC';
export const LEDGER_DETECTED = 'src/WalletHOC/LEDGER_DETECTED';
export const FETCH_LEDGER_ADDRESSES = 'src/WalletHOC/FETCH_LEDGER_ADDRESSES';
export const FETCHED_LEDGER_ADDRESS = 'src/WalletHOC/FETCHED_LEDGER_ADDRESS';
export const SAVE_LEDGER_ADDRESS = 'src/WalletHOC/SAVE_LEDGER_ADDRESS';

export const LEDGER_ERROR = 'src/WalletHOC/LEDGER_ERROR';

export const TRANSACTION_CONFIRMED = 'src/WalletHOC/TRANSACTION_CONFIRMED';

export const DELETE_WALLET = 'src/WalletHOC/DELETE_WALLET';

export const RESET_DECRYPT_WALLET_CALLBACK = 'src/WalletHOC/RESET_DECRYPT_WALLET_CALLBACK';

