export const LOAD_EXCHANGE_RATE = 'app/ExchangeRate/LOAD_EXCHANGE_RATE';
export const LOAD_EXCHANGE_RATE_SUCCESS = 'app/ExchangeRate/LOAD_EXCHANGE_RATE_SUCCESS';
export const LOAD_EXCHANGE_RATE_FAILURE = 'app/ExchangeRate/LOAD_EXCHANGE_RATE_FAILURE';
export const LOAD_TICKERS_SUCCESS = 'app/ExchangeRate/LOAD_TICKERS_SUCCESS';
export const LOAD_TICKERS_FAILURE = 'app/ExchangeRate/LOAD_TICKERS_FAILURE';
