export const DEFAULT_LOCALE = 'en';

export const NOTIFY = 'src/App/NOTIFY';
export const CHANGE_NETWORK = 'src/App/CHANGE_NETWORK';
export const INIT_NAHMII_PROVIDERS = 'src/App/INIT_NAHMII_PROVIDERS';
export const UPDATE_NAHMII_PROVIDER = 'src/App/UPDATE_NAHMII_PROVIDER';
export const UPDATE_CURRENT_NETWORK_NAHMII_PROVIDER = 'src/App/UPDATE_CURRENT_NETWORK_NAHMII_PROVIDER';

export const INIT_NETWORK_ACTIVITY = 'src/App/INIT_NETWORK_ACTIVITY';

export const BATCH_EXPORT = 'src/App/BATCH_EXPORT';
export const BATCH_EXPORT_SUCCESS = 'src/App/BATCH_EXPORT_SUCCESS';
export const BATCH_EXPORT_ERROR = 'src/App/BATCH_EXPORT_ERROR';
export const BATCH_IMPORT = 'src/App/BATCH_IMPORT';
export const BATCH_IMPORT_SUCCESS = 'src/App/BATCH_IMPORT_SUCCESS';
export const BATCH_IMPORT_ERROR = 'src/App/BATCH_IMPORT_ERROR';
export const DECRYPT_IMPORT = 'src/App/DECRYPT_IMPORT';
export const DECRYPT_IMPORT_SUCCESS = 'src/App/DECRYPT_IMPORT_SUCCESS';
export const DECRYPT_IMPORT_ERROR = 'src/App/DECRYPT_IMPORT_ERROR';
