export const DEFAULT_LOCALE = 'en';

export const NOTIFY = 'src/App/NOTIFY';
export const CHANGE_NETWORK = 'src/App/CHANGE_NETWORK';

export const INIT_NETWORK_ACTIVITY = 'src/App/INIT_NETWORK_ACTIVITY';

export const LOAD_IDENTITY_SERVICE_TOKEN_SUCCESS = 'src/App/LOAD_IDENTITY_SERVICE_TOKEN_SUCCESS';
