export const DEFAULT_LOCALE = 'en';

export const NOTIFY = 'src/App/NOTIFY';
export const CHANGE_NETWORK = 'src/App/CHANGE_NETWORK';
export const INIT_NAHMII_PROVIDERS = 'src/App/INIT_NAHMII_PROVIDERS';
export const UPDATE_NAHMII_PROVIDER = 'src/App/UPDATE_NAHMII_PROVIDER';
export const UPDATE_CURRENT_NETWORK_NAHMII_PROVIDER = 'src/App/UPDATE_CURRENT_NETWORK_NAHMII_PROVIDER';

export const INIT_NETWORK_ACTIVITY = 'src/App/INIT_NETWORK_ACTIVITY';
