
export const LOAD_PRICE_HISTORY = 'src/dex/LOAD_PRICE_HISTORY';
export const LOAD_PRICE_HISTORY_SUCCESS = 'src/dex/LOAD_PRICE_HISTORY_SUCCESS';
export const LOAD_PRICE_HISTORY_ERROR = 'src/dex/LOAD_PRICE_HISTORY_ERROR';
export const LISTEN_LATEST_PRICE = 'src/dex/LISTEN_LATEST_PRICE';
export const UPDATE_LATEST_PRICE_SUCCESS = 'src/dex/UPDATE_LATEST_PRICE_SUCCESS';
export const UPDATE_LATEST_PRICE_ERROR = 'src/dex/UPDATE_LATEST_PRICE_ERROR';
