export const LOAD_STRIIM_ACCOUNTS = 'src/StriimAccounts/LOAD_STRIIM_ACCOUNTS';
export const LOAD_STRIIM_ACCOUNTS_SUCCESS = 'src/StriimAccounts/LOAD_STRIIM_ACCOUNTS_SUCCESS';
export const LOAD_STRIIM_ACCOUNTS_FAILURE = 'src/StriimAccounts/LOAD_STRIIM_ACCOUNTS_FAILURE';
export const CHANGE_CURRENT_ACCOUNT = 'src/StriimAccounts/CHANGE_CURRENT_ACCOUNT';
export const CHANGE_CURRENT_CURRENCY = 'src/StriimAccounts/CHANGE_CURRENT_CURRENCY';
